package com.ecommerce.model.notification;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CANCELLED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    APPOINTMENT_BOOKED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,
    DRIVER_ASSIGN,
    DRIVER_REGISTRATION,
    PASSWORD_CHANGE,
    ORDER_STARTED,
    INSTORE_PURCHASE,
    STAFF_LEAVE
}
